export const actions = {
  ON_ADD: 'ON_ADD',
  ON_GET_ONE: 'ON_GET_ONE',
  ON_GET_ALL: 'ON_GET_ALL',
  ON_UPDATE: 'ON_UPDATE',
  ON_DELETE: 'ON_DELETE',
  ON_LOGIN: 'ON_LOGIN',
  ON_LOGOUT: 'ON_LOGOUT',
  CHECK_AUTH: 'CHECK_AUTH',
}
