const events = {
  speculation: {
    create: 'createSpeculation',
    getAll: 'getAllSpeculations',
    update: 'updateSpeculation',
    delete: 'deleteSpeculation',
    getOne: 'getOneSpeculation',
  },
  speculationInstitution: {
    create: 'createSpeculationInstitution',
    getAll: 'getAllSpeculationsInstitution',
    update: 'updateSpeculationInstitution',
    delete: 'deleteSpeculationInstitution',
    getOne: 'getOneSpeculationInstitution',
  },
  variete: {
    create: 'createVariete',
    getAll: 'getAllVarietes',
    update: 'updateVariete',
    delete: 'deleteVariete',
    getOne: 'getOneVariete',
  },
  varieteInstitution: {
    create: 'createVarieteInstitution',
    getAll: 'getAllVarietesInstitution',
    update: 'updateVarieteInstitution',
    delete: 'deleteVarieteInstitution',
    getOne: 'getOneVarieteInstitution',
  },
  commande: {
    create: 'createCommande',
    getAll: 'getAllCommandes',
    update: 'updateCommande',
    delete: 'deleteCommande',
    getOne: 'getOneCommande',
  },
  client: {
    create: 'createClient',
    getAll: 'getAllClients',
    update: 'updateClient',
    delete: 'deleteClient',
    getOne: 'getOneClient',
  },
  zoneAgro: {
    create: 'createZoneAgro',
    getAll: 'getAllZoneAgros',
    update: 'updateZoneAgro',
    delete: 'deleteZoneAgro',
    getOne: 'getOneZoneAgro',
  },
  zoneInstitution: {
    create: 'createZoneInstitution',
    getAll: 'getAllZoneInstitutions',
    update: 'updateZoneInstitution',
    delete: 'deleteZoneInstitution',
    getOne: 'getOneZoneInstitution',
  },
  contact: {
    create: 'createContact',
    getAll: 'getAllContacts',
    update: 'updateContact',
    delete: 'deleteContact',
    getOne: 'getOneContact',
  },
  institution: {
    create: 'createInstitution',
    getAll: 'getAllInstitutions',
    update: 'updateInstitution',
    delete: 'deleteInstitution',
    getOne: 'getOneInstitution',
  },
  localisation: {
    create: 'createLocalisation',
    getAll: 'getAllLocalisations',
    update: 'updateLocalisation',
    delete: 'deleteLocalisation',
    getOne: 'getOneLocalisation',
  },
  magasin: {
    create: 'createMagasin',
    getAll: 'getAllMagasins',
    update: 'updateMagasin',
    delete: 'deleteMagasin',
    getOne: 'getOneMagasin',
  },
  niveauDeProduction: {
    create: 'createNiveauDeProduction',
    getAll: 'getAllNiveauDeProductions',
    update: 'updateNiveauDeProduction',
    delete: 'deleteNiveauDeProduction',
    getOne: 'getOneNiveauDeProduction',
  },
  niveauInstitution: {
    create: 'createNiveauInstitution',
    getAll: 'getAllNiveauInstitutions',
    update: 'updateNiveauInstitution',
    delete: 'deleteNiveauInstitution',
    getOne: 'getOneNiveauInstitution',
  },
  production: {
    create: 'createProduction',
    getAll: 'getAllProductions',
    update: 'updateProduction',
    delete: 'deleteProduction',
    getOne: 'getOneProduction',
  },
  imageDialog: {
    openImageDialog: "openImageDialog",
  }
}

const eventResponse = {
  speculation: {
    created: 'createdSpeculation',
    gotAll: 'gotAllSpeculations',
    updated: 'updatedSpeculation',
    deleted: 'deletedSpeculation',
    gotOne: 'gdtOneSpeculation',
  },
  speculationInstitution: {
    created: 'createdSpeculationInstitution',
    gotAll: 'gotAllSpeculationsInstitution',
    updated: 'updatedSpeculationInstitution',
    deleted: 'deletedSpeculationInstitution',
    gotOne: 'gotOneSpeculationInstitution',
  },
  variete: {
    created: 'createdVariete',
    gotAll: 'gotAllVarietes',
    updated: 'updatedVariete',
    deleted: 'deletedVariete',
    gotOne: 'gotOneVariete',
  },
  varieteInstitution: {
    created: 'createdVarieteInstitution',
    gotAll: 'gotAllVarietesInstitution',
    updated: 'updatedVarieteInstitution',
    deleted: 'deletedVarieteInstitution',
    gotOne: 'gotOneVarieteInstitution',
  },
  commande: {
    created: 'createdCommande',
    gotAll: 'gotAllCommandes',
    updated: 'updatedCommande',
    deleted: 'deletedCommande',
    gotOne: 'gotOneCommande',
  },
  client: {
    created: 'createdClient',
    gotAll: 'gotAllClients',
    updated: 'updatedClient',
    deleted: 'deletedClient',
    gotOne: 'gotOneClient',
  },
  zoneAgro: {
    created: 'createdZoneAgro',
    gotAll: 'gotAllZoneAgros',
    updated: 'updatedZoneAgro',
    deleted: 'deletedZoneAgro',
    gotOne: 'gotOneZoneAgro',
  },
  zoneInstitution: {
    created: 'createdZoneInstitution',
    gotAll: 'gotAllZoneInstitutions',
    updated: 'updatedZoneInstitution',
    deleted: 'deletedZoneInstitution',
    gotOne: 'gotOneZoneInstitution',
  },
  contact: {
    created: 'createdContact',
    gotAll: 'gotAllContacts',
    updated: 'updatedContact',
    deleted: 'deletedContact',
    gotOne: 'gotOneContact',
  },
  institution: {
    created: 'createdInstitution',
    gotAll: 'gotAllInstitutions',
    updated: 'updatedInstitution',
    deleted: 'deletedInstitution',
    gotOne: 'gotOneInstitution',
  },
  localisation: {
    created: 'createdLocalisation',
    gotAll: 'gotAllLocalisations',
    updated: 'updatedLocalisation',
    deleted: 'deletedLocalisation',
    gotOne: 'gotOneLocalisation',
  },
  magasin: {
    created: 'createdMagasin',
    gotAll: 'gotAllMagasins',
    updated: 'updatedMagasin',
    deleted: 'deletedMagasin',
    gotOne: 'gotOneMagasin',
  },
  niveauDeProduction: {
    created: 'createdNiveauDeProduction',
    gotAll: 'gotAllNiveauDeProductions',
    updated: 'updatedNiveauDeProduction',
    deleted: 'deletedNiveauDeProduction',
    gotOne: 'gotOneNiveauDeProduction',
  },
  niveauInstitution: {
    created: 'createdNiveauInstitution',
    gotAll: 'gotAllNiveauInstitutions',
    updated: 'updatedNiveauInstitution',
    deleted: 'deletedNiveauInstitution',
    gotOne: 'gotOneNiveauInstitution',
  },
  production: {
    created: 'createdProduction',
    gotAll: 'gotAllProductions',
    updated: 'updatedProduction',
    deleted: 'deletedProduction',
    gotOne: 'gotOneProduction',
  },
  imageDialog: {
    closedImageDialog: "closedImageDialog",
  }
}

module.exports = {
  events,
  eventResponse,
}
